# permissions for end users to edit bookingsds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bookingsd-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bookings-operator
    app.kubernetes.io/part-of: bookings-operator
    app.kubernetes.io/managed-by: kustomize
  name: bookingsd-editor-role
rules:
- apiGroups:
  - cache.calvarado04.com
  resources:
  - bookingsds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.calvarado04.com
  resources:
  - bookingsds/status
  verbs:
  - get
